<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Disciplina.aspx.cs" Inherits="Banco.Disciplina" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <br />
    <h3>
        <asp:Label ID="lblMain" runat="server" Text="Inserir uma nova disciplina: "></asp:Label> <br />
    </h3>
    <asp:TextBox ID="txtNome" runat="server" />
    <asp:Button ID="btnInserir" Text="Gravar no banco" runat="server" OnClientClick="alert(msg)" OnClick="btnInserir_Click" /> <br /> <br />
    <asp:Label ID="lblResultado" Text="" runat="server" />
    <h3>
        <asp:Label Text="Disciplinas cadastradas:" runat="server" />
    </h3>
    <asp:GridView ID="gridDisciplina" DataKeyNames="id" runat="server" AutoGenerateColumns="false" CellPadding="10" CellSpacing="10" AllowPaging="true"
        PageSize="5" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" OnPageIndexChanging="gridDisciplina_PageIndexChanging" OnRowEditing="gridDisciplina_RowEditing" 
        OnRowDeleting="gridDisciplina_RowDeleting" OnRowCancelingEdit="gridDisciplina_RowCancelingEdit" OnRowUpdating="gridDisciplina_RowUpdating" EmptyDataText="Nenhuma disciplina cadastrada."
        >
        <Columns>
            <asp:BoundField DataField="nome" HeaderText="Nome" />
        </Columns>
    </asp:GridView>
</asp:Content>
